version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:latest
      
    working_directory: ~/go/src/github.com/ferhdz95/go-cards/cards

    steps:
      - checkout
      #Added library to convert test to xml
      - run: go get github.com/jstemmer/go-junit-report
      
      - run: ls
      
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report cards/go-test.out > cards/go-test-report.xml" EXIT
            go test ./cards | tee go-test.out
